[window.padding]
x = 5
y = 0

[font]
size = 12

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Light"

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#282c34"
foreground = "#bbc2cf"
dim_foreground = "#5b6268"
bright_foreground = "#bbc2cf"

[colors.cursor]
text = "#282c34"
cursor = "#a9a1e1"

[colors.vi_mode_cursor]
text = "#282c34"
cursor = "#b7bdf8"

[colors.search.matches]
foreground = "#282c34"
background = "#73797e"

[colors.search.focused_match]
foreground = "#282c34"
background = "#98be65"

[colors.footer_bar]
foreground = "#282c34"
background = "#73797e"

[colors.hints.start]
foreground = "#282c34"
background = "#ecbe7b"

[colors.hints.end]
foreground = "#282c34"
background = "#73797e"

[colors.selection]
text = "#282c34"
background = "#a9a1e1"

[colors.normal]
black = "#5b6268"
red = "#ff6c6b"
green = "#98be65"
yellow = "#ecbe7b"
blue = "#51afef"
magenta = "#c678dd"
cyan = "#4db5bd"
white = "#9ca0a4"

[colors.bright]
black = "#73797e"
red = "#ff6c6b"
green = "#98be65"
yellow = "#ecbe7b"
blue = "#51afef"
magenta = "#c678dd"
cyan = "#4db5bd"
white = "#73797e"

[[colors.indexed_colors]]
index = 16
color = "#da8548"

[[colors.indexed_colors]]
index = 17
color = "#a9a1e1"
